//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyResumeWebsite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experiences
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string CompanyName { get; set; }
        public string Date { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
